insert into Categories (Id, Name) values ('PG', 'Kamberatoro Airport');
insert into Categories (Id, Name) values ('AR', 'Martin Miguel De Guemes International Airport');
insert into Categories (Id, Name) values ('GQ', 'Médouneu Airport');
insert into Categories (Id, Name) values ('AR', 'La Cumbre Airport');
insert into Categories (Id, Name) values ('AR', 'Brigadier D.H.E. Ruiz Airport');
insert into Categories (Id, Name) values ('NO', 'Stavanger Airport Sola');
insert into Categories (Id, Name) values ('US', 'Telida Airport');
insert into Categories (Id, Name) values ('US', 'Keokuk Municipal Airport');
insert into Categories (Id, Name) values ('KE', 'Amboseli Airport');
insert into Categories (Id, Name) values ('NZ', 'Glentanner Airport');
insert into Categories (Id, Name) values ('PA', 'Yaviza Airport');
insert into Categories (Id, Name) values ('US', 'Durango La Plata County Airport');
insert into Categories (Id, Name) values ('US', 'George Bush Intercontinental Houston Airport');
insert into Categories (Id, Name) values ('RU', 'Migalovo Air Base');
insert into Categories (Id, Name) values ('US', 'Port Alice Seaplane Base');
insert into Categories (Id, Name) values ('DO', 'Maria Montez International Airport');
insert into Categories (Id, Name) values ('ID', 'Kiman Airport');
insert into Categories (Id, Name) values ('CN', 'Cangyuan Washan Airport');
insert into Categories (Id, Name) values ('US', 'Page Field');
insert into Categories (Id, Name) values ('WS', 'Asau Airport');
insert into Categories (Id, Name) values ('US', 'Mobile Downtown Airport');
insert into Categories (Id, Name) values ('NL', 'Amsterdam Airport Schiphol');
insert into Categories (Id, Name) values ('BR', 'Usina Catanduva Airport');
insert into Categories (Id, Name) values ('KE', 'Mandera Airport');
insert into Categories (Id, Name) values ('GB', 'Sanday Airport');
insert into Categories (Id, Name) values ('PG', 'Chimbu Airport');
insert into Categories (Id, Name) values ('AU', 'Silver Plains Airport');
insert into Categories (Id, Name) values ('US', 'Fairbanks International Airport');
insert into Categories (Id, Name) values ('BR', 'Hotel Transamérica Airport');
insert into Categories (Id, Name) values ('JP', 'Matsuyama Airport');
insert into Categories (Id, Name) values ('PG', 'Laiagam Airport');
insert into Categories (Id, Name) values ('MN', 'Tselserleg Airport');
insert into Categories (Id, Name) values ('NA', 'Mount Etjo Airport');
insert into Categories (Id, Name) values ('ML', 'Nioro du Sahel Airport');
insert into Categories (Id, Name) values ('US', 'Sheppard Air Force Base-Wichita Falls Municipal Airport');
insert into Categories (Id, Name) values ('PG', 'Heiweni Airport');
insert into Categories (Id, Name) values ('JP', 'Takamatsu Airport');
insert into Categories (Id, Name) values ('MY', 'Sitiawan Airport');
insert into Categories (Id, Name) values ('SL', 'Bo Airport');
insert into Categories (Id, Name) values ('US', 'South Jersey Regional Airport');
insert into Categories (Id, Name) values ('MH', 'Maloelap Island Airport');
insert into Categories (Id, Name) values ('UA', 'Khmelnytskyi Airport');
insert into Categories (Id, Name) values ('PG', 'Ialibu Airport');
insert into Categories (Id, Name) values ('BR', 'Barcelos Airport');
insert into Categories (Id, Name) values ('DE', 'Hamburg-Finkenwerder Airport');
insert into Categories (Id, Name) values ('PG', 'Param Airport');
insert into Categories (Id, Name) values ('FR', 'Clermont-Ferrand Auvergne Airport');
insert into Categories (Id, Name) values ('BR', 'Patos de Minas Airport');
insert into Categories (Id, Name) values ('MA', 'Beni Mellal Airport');
insert into Categories (Id, Name) values ('AU', 'Mallacoota Airport');
insert into Categories (Id, Name) values ('ID', 'El Tari Airport');
insert into Categories (Id, Name) values ('AU', 'Marion Downs Airport');
insert into Categories (Id, Name) values ('AR', 'Saenz Peña Airport');
insert into Categories (Id, Name) values ('VG', 'Captain Auguste George Airport');
insert into Categories (Id, Name) values ('ID', 'Buluh Tumbang (H A S Hanandjoeddin) Airport');
insert into Categories (Id, Name) values ('CR', 'Los Chiles Airport');
insert into Categories (Id, Name) values ('ID', 'Sungai Pakning Bengkalis Airport');
insert into Categories (Id, Name) values ('RU', 'Barnaul Airport');
insert into Categories (Id, Name) values ('BR', 'Buriti Alegre Airport');
insert into Categories (Id, Name) values ('JP', 'Iwo Jima Airport');
insert into Categories (Id, Name) values ('MN', 'Tosontsengel Airport');
insert into Categories (Id, Name) values ('PA', 'Capt Justiniano Montenegro Airport');
insert into Categories (Id, Name) values ('CO', 'La Pedrera Airport');
insert into Categories (Id, Name) values ('US', 'Grand Canyon National Park Airport');
insert into Categories (Id, Name) values ('ZM', 'Chipata Airport');
insert into Categories (Id, Name) values ('US', 'Beaumont Municipal Airport');
insert into Categories (Id, Name) values ('US', 'TSTC Waco Airport');
insert into Categories (Id, Name) values ('US', 'Monticello Airport');
insert into Categories (Id, Name) values ('NL', 'Rotterdam The Hague Airport');
insert into Categories (Id, Name) values ('PG', 'Menyamya Airport');
insert into Categories (Id, Name) values ('AU', 'Mount Swan Airport');
insert into Categories (Id, Name) values ('AU', 'Chinchilla Airport');
insert into Categories (Id, Name) values ('VE', 'Mayor Buenaventura Vivas International Airport');
insert into Categories (Id, Name) values ('RU', 'Barnaul Airport');
insert into Categories (Id, Name) values ('AU', 'Wiluna Airport');
insert into Categories (Id, Name) values ('US', 'Alexander Field South Wood County Airport');
insert into Categories (Id, Name) values ('AU', 'Forster (Wallis Is) Airport');
insert into Categories (Id, Name) values ('US', 'North Fork Valley Airport');
insert into Categories (Id, Name) values ('CN', 'Anqing Tianzhushan Airport');
insert into Categories (Id, Name) values ('PH', 'Casiguran Airport');
insert into Categories (Id, Name) values ('US', 'Eastland Municipal Airport');
insert into Categories (Id, Name) values ('ZA', 'Zulu Inyala Airport');
insert into Categories (Id, Name) values ('AU', 'Camooweal Airport');
insert into Categories (Id, Name) values ('NP', 'Langtang Airport');
insert into Categories (Id, Name) values ('PG', 'Margarima Airport');
insert into Categories (Id, Name) values ('AU', 'Gove Airport');
insert into Categories (Id, Name) values ('PF', 'Nukutepipi Airport');
insert into Categories (Id, Name) values ('US', 'Tri-State/Milton J. Ferguson Field');
insert into Categories (Id, Name) values ('NO', 'Narvik Framnes Airport');
insert into Categories (Id, Name) values ('BS', 'Great Harbour Cay Airport');
insert into Categories (Id, Name) values ('ID', 'Binaka Airport');
insert into Categories (Id, Name) values ('CA', 'Charlottetown Airport');
insert into Categories (Id, Name) values ('CO', 'Jorge E. Gonzalez Torres Airport');
insert into Categories (Id, Name) values ('ID', 'Wahai,Seram Island');
insert into Categories (Id, Name) values ('US', 'Togiak Airport');
insert into Categories (Id, Name) values ('PG', 'Mougulu Airport');
insert into Categories (Id, Name) values ('US', 'Chuathbaluk Airport');
insert into Categories (Id, Name) values ('MP', 'Tinian International Airport');
insert into Categories (Id, Name) values ('ID', 'Bade Airport');
insert into Categories (Id, Name) values ('BR', 'Cascavel Airport');
